name: PitRemake
authors:
  - Kyro
  - Wiji
version: 1.0.0
main: dev.kyro.pitsim.PitSim
description: Remake of the Hypixel Pit
depend:
  - Citizens
  - Vault
  - PlaceholderAPI
  - NoteBlockAPI
  - ProtocolLib
commands:
  pitsim:
  ps:
  oof:
  atest:
  enchant:
  fresh:
  non:
  show:
  perks:
  jewel:
  market:
  enchants:
  togglestereo:
  donator:
  renown:
  spawn:
  crategive:
  cg:
  afk:
  check:
  shop:
  store:
  discord:
  disc:
  booster:
  boostergive:
  vn: